OPENAI_API_KEY = "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"  # Replace with your actual OpenAI API key
