OPENAI_API_KEY = "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"  # Replace with your actual OpenAI API key
